name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore "./proyecto-si8811a-2024-ii-u1-apis-y-funciones-jarro-y-valle.csproj"

      - name: Build project
        run: dotnet build --configuration Release --no-restore "./proyecto-si8811a-2024-ii-u1-apis-y-funciones-jarro-y-valle.csproj"

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Build Docker image
        run: |
          docker build -t eventos_vj:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 9091:9091 eventos_vj:latest
